// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteSnapshotsSsIDReapHandlerFunc turns a function with the right signature into a delete snapshots ss ID reap handler
type DeleteSnapshotsSsIDReapHandlerFunc func(DeleteSnapshotsSsIDReapParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteSnapshotsSsIDReapHandlerFunc) Handle(params DeleteSnapshotsSsIDReapParams) middleware.Responder {
	return fn(params)
}

// DeleteSnapshotsSsIDReapHandler interface for that can handle valid delete snapshots ss ID reap params
type DeleteSnapshotsSsIDReapHandler interface {
	Handle(DeleteSnapshotsSsIDReapParams) middleware.Responder
}

// NewDeleteSnapshotsSsIDReap creates a new http.Handler for the delete snapshots ss ID reap operation
func NewDeleteSnapshotsSsIDReap(ctx *middleware.Context, handler DeleteSnapshotsSsIDReapHandler) *DeleteSnapshotsSsIDReap {
	return &DeleteSnapshotsSsIDReap{Context: ctx, Handler: handler}
}

/*
	DeleteSnapshotsSsIDReap swagger:route DELETE /snapshots/{ssId}/reap deleteSnapshotsSsIdReap

delete reap state
*/
type DeleteSnapshotsSsIDReap struct {
	Context *middleware.Context
	Handler DeleteSnapshotsSsIDReapHandler
}

func (o *DeleteSnapshotsSsIDReap) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteSnapshotsSsIDReapParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DeleteSnapshotsSsIDReapBadRequestBody delete snapshots ss ID reap bad request body
//
// swagger:model DeleteSnapshotsSsIDReapBadRequestBody
type DeleteSnapshotsSsIDReapBadRequestBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this delete snapshots ss ID reap bad request body
func (o *DeleteSnapshotsSsIDReapBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete snapshots ss ID reap bad request body based on context it is used
func (o *DeleteSnapshotsSsIDReapBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteSnapshotsSsIDReapBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteSnapshotsSsIDReapBadRequestBody) UnmarshalBinary(b []byte) error {
	var res DeleteSnapshotsSsIDReapBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
