// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetSnapshotsSsIDMincoreOKCode is the HTTP code returned for type GetSnapshotsSsIDMincoreOK
const GetSnapshotsSsIDMincoreOKCode int = 200

/*
GetSnapshotsSsIDMincoreOK Mincore state

swagger:response getSnapshotsSsIdMincoreOK
*/
type GetSnapshotsSsIDMincoreOK struct {

	/*
	  In: Body
	*/
	Payload *GetSnapshotsSsIDMincoreOKBody `json:"body,omitempty"`
}

// NewGetSnapshotsSsIDMincoreOK creates GetSnapshotsSsIDMincoreOK with default headers values
func NewGetSnapshotsSsIDMincoreOK() *GetSnapshotsSsIDMincoreOK {

	return &GetSnapshotsSsIDMincoreOK{}
}

// WithPayload adds the payload to the get snapshots ss Id mincore o k response
func (o *GetSnapshotsSsIDMincoreOK) WithPayload(payload *GetSnapshotsSsIDMincoreOKBody) *GetSnapshotsSsIDMincoreOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get snapshots ss Id mincore o k response
func (o *GetSnapshotsSsIDMincoreOK) SetPayload(payload *GetSnapshotsSsIDMincoreOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSnapshotsSsIDMincoreOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSnapshotsSsIDMincoreBadRequestCode is the HTTP code returned for type GetSnapshotsSsIDMincoreBadRequest
const GetSnapshotsSsIDMincoreBadRequestCode int = 400

/*
GetSnapshotsSsIDMincoreBadRequest Invalid request

swagger:response getSnapshotsSsIdMincoreBadRequest
*/
type GetSnapshotsSsIDMincoreBadRequest struct {

	/*
	  In: Body
	*/
	Payload *GetSnapshotsSsIDMincoreBadRequestBody `json:"body,omitempty"`
}

// NewGetSnapshotsSsIDMincoreBadRequest creates GetSnapshotsSsIDMincoreBadRequest with default headers values
func NewGetSnapshotsSsIDMincoreBadRequest() *GetSnapshotsSsIDMincoreBadRequest {

	return &GetSnapshotsSsIDMincoreBadRequest{}
}

// WithPayload adds the payload to the get snapshots ss Id mincore bad request response
func (o *GetSnapshotsSsIDMincoreBadRequest) WithPayload(payload *GetSnapshotsSsIDMincoreBadRequestBody) *GetSnapshotsSsIDMincoreBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get snapshots ss Id mincore bad request response
func (o *GetSnapshotsSsIDMincoreBadRequest) SetPayload(payload *GetSnapshotsSsIDMincoreBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSnapshotsSsIDMincoreBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
