// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ucsdsysnet/faasnap/models"
)

// GetVmsVMIDOKCode is the HTTP code returned for type GetVmsVMIDOK
const GetVmsVMIDOKCode int = 200

/*
GetVmsVMIDOK OK

swagger:response getVmsVmIdOK
*/
type GetVmsVMIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.VM `json:"body,omitempty"`
}

// NewGetVmsVMIDOK creates GetVmsVMIDOK with default headers values
func NewGetVmsVMIDOK() *GetVmsVMIDOK {

	return &GetVmsVMIDOK{}
}

// WithPayload adds the payload to the get vms Vm Id o k response
func (o *GetVmsVMIDOK) WithPayload(payload *models.VM) *GetVmsVMIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get vms Vm Id o k response
func (o *GetVmsVMIDOK) SetPayload(payload *models.VM) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetVmsVMIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetVmsVMIDBadRequestCode is the HTTP code returned for type GetVmsVMIDBadRequest
const GetVmsVMIDBadRequestCode int = 400

/*
GetVmsVMIDBadRequest Invalid request

swagger:response getVmsVmIdBadRequest
*/
type GetVmsVMIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *GetVmsVMIDBadRequestBody `json:"body,omitempty"`
}

// NewGetVmsVMIDBadRequest creates GetVmsVMIDBadRequest with default headers values
func NewGetVmsVMIDBadRequest() *GetVmsVMIDBadRequest {

	return &GetVmsVMIDBadRequest{}
}

// WithPayload adds the payload to the get vms Vm Id bad request response
func (o *GetVmsVMIDBadRequest) WithPayload(payload *GetVmsVMIDBadRequestBody) *GetVmsVMIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get vms Vm Id bad request response
func (o *GetVmsVMIDBadRequest) SetPayload(payload *GetVmsVMIDBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetVmsVMIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
