// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetUIDataOKCode is the HTTP code returned for type GetUIDataOK
const GetUIDataOKCode int = 200

/*
GetUIDataOK ok

swagger:response getUiDataOK
*/
type GetUIDataOK struct {
}

// NewGetUIDataOK creates GetUIDataOK with default headers values
func NewGetUIDataOK() *GetUIDataOK {

	return &GetUIDataOK{}
}

// WriteResponse to the client
func (o *GetUIDataOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
