// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetVmsHandlerFunc turns a function with the right signature into a get vms handler
type GetVmsHandlerFunc func(GetVmsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetVmsHandlerFunc) Handle(params GetVmsParams) middleware.Responder {
	return fn(params)
}

// GetVmsHandler interface for that can handle valid get vms params
type GetVmsHandler interface {
	Handle(GetVmsParams) middleware.Responder
}

// NewGetVms creates a new http.Handler for the get vms operation
func NewGetVms(ctx *middleware.Context, handler GetVmsHandler) *GetVms {
	return &GetVms{Context: ctx, Handler: handler}
}

/*
	GetVms swagger:route GET /vms getVms

Returns a list of active VMs
*/
type GetVms struct {
	Context *middleware.Context
	Handler GetVmsHandler
}

func (o *GetVms) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetVmsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
