// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetUIOKCode is the HTTP code returned for type GetUIOK
const GetUIOKCode int = 200

/*
GetUIOK ok

swagger:response getUiOK
*/
type GetUIOK struct {
}

// NewGetUIOK creates GetUIOK with default headers values
func NewGetUIOK() *GetUIOK {

	return &GetUIOK{}
}

// WriteResponse to the client
func (o *GetUIOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
