// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ucsdsysnet/faasnap/models"
)

// GetFunctionsOKCode is the HTTP code returned for type GetFunctionsOK
const GetFunctionsOKCode int = 200

/*
GetFunctionsOK List of functions

swagger:response getFunctionsOK
*/
type GetFunctionsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Function `json:"body,omitempty"`
}

// NewGetFunctionsOK creates GetFunctionsOK with default headers values
func NewGetFunctionsOK() *GetFunctionsOK {

	return &GetFunctionsOK{}
}

// WithPayload adds the payload to the get functions o k response
func (o *GetFunctionsOK) WithPayload(payload []*models.Function) *GetFunctionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get functions o k response
func (o *GetFunctionsOK) SetPayload(payload []*models.Function) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFunctionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Function, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
