// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetUIDataHandlerFunc turns a function with the right signature into a get UI data handler
type GetUIDataHandlerFunc func(GetUIDataParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUIDataHandlerFunc) Handle(params GetUIDataParams) middleware.Responder {
	return fn(params)
}

// GetUIDataHandler interface for that can handle valid get UI data params
type GetUIDataHandler interface {
	Handle(GetUIDataParams) middleware.Responder
}

// NewGetUIData creates a new http.Handler for the get UI data operation
func NewGetUIData(ctx *middleware.Context, handler GetUIDataHandler) *GetUIData {
	return &GetUIData{Context: ctx, Handler: handler}
}

/*
	GetUIData swagger:route GET /ui/data getUiData

UI
*/
type GetUIData struct {
	Context *middleware.Context
	Handler GetUIDataHandler
}

func (o *GetUIData) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetUIDataParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
