// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ucsdsysnet/faasnap/models"
)

// GetVmsOKCode is the HTTP code returned for type GetVmsOK
const GetVmsOKCode int = 200

/*
GetVmsOK OK

swagger:response getVmsOK
*/
type GetVmsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.VM `json:"body,omitempty"`
}

// NewGetVmsOK creates GetVmsOK with default headers values
func NewGetVmsOK() *GetVmsOK {

	return &GetVmsOK{}
}

// WithPayload adds the payload to the get vms o k response
func (o *GetVmsOK) WithPayload(payload []*models.VM) *GetVmsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get vms o k response
func (o *GetVmsOK) SetPayload(payload []*models.VM) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetVmsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.VM, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
