// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetSnapshotsSsIDReapParams creates a new GetSnapshotsSsIDReapParams object
//
// There are no default values defined in the spec.
func NewGetSnapshotsSsIDReapParams() GetSnapshotsSsIDReapParams {

	return GetSnapshotsSsIDReapParams{}
}

// GetSnapshotsSsIDReapParams contains all the bound params for the get snapshots ss ID reap operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetSnapshotsSsIDReap
type GetSnapshotsSsIDReapParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	SsID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetSnapshotsSsIDReapParams() beforehand.
func (o *GetSnapshotsSsIDReapParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rSsID, rhkSsID, _ := route.Params.GetOK("ssId")
	if err := o.bindSsID(rSsID, rhkSsID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSsID binds and validates parameter SsID from path.
func (o *GetSnapshotsSsIDReapParams) bindSsID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.SsID = raw

	return nil
}
