// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PatchSnapshotsSsIDMincoreOKCode is the HTTP code returned for type PatchSnapshotsSsIDMincoreOK
const PatchSnapshotsSsIDMincoreOKCode int = 200

/*
PatchSnapshotsSsIDMincoreOK OK

swagger:response patchSnapshotsSsIdMincoreOK
*/
type PatchSnapshotsSsIDMincoreOK struct {
}

// NewPatchSnapshotsSsIDMincoreOK creates PatchSnapshotsSsIDMincoreOK with default headers values
func NewPatchSnapshotsSsIDMincoreOK() *PatchSnapshotsSsIDMincoreOK {

	return &PatchSnapshotsSsIDMincoreOK{}
}

// WriteResponse to the client
func (o *PatchSnapshotsSsIDMincoreOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PatchSnapshotsSsIDMincoreBadRequestCode is the HTTP code returned for type PatchSnapshotsSsIDMincoreBadRequest
const PatchSnapshotsSsIDMincoreBadRequestCode int = 400

/*
PatchSnapshotsSsIDMincoreBadRequest Invalid request

swagger:response patchSnapshotsSsIdMincoreBadRequest
*/
type PatchSnapshotsSsIDMincoreBadRequest struct {

	/*
	  In: Body
	*/
	Payload *PatchSnapshotsSsIDMincoreBadRequestBody `json:"body,omitempty"`
}

// NewPatchSnapshotsSsIDMincoreBadRequest creates PatchSnapshotsSsIDMincoreBadRequest with default headers values
func NewPatchSnapshotsSsIDMincoreBadRequest() *PatchSnapshotsSsIDMincoreBadRequest {

	return &PatchSnapshotsSsIDMincoreBadRequest{}
}

// WithPayload adds the payload to the patch snapshots ss Id mincore bad request response
func (o *PatchSnapshotsSsIDMincoreBadRequest) WithPayload(payload *PatchSnapshotsSsIDMincoreBadRequestBody) *PatchSnapshotsSsIDMincoreBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch snapshots ss Id mincore bad request response
func (o *PatchSnapshotsSsIDMincoreBadRequest) SetPayload(payload *PatchSnapshotsSsIDMincoreBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchSnapshotsSsIDMincoreBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
