// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewPatchSnapshotsSsIDReapParams creates a new PatchSnapshotsSsIDReapParams object
//
// There are no default values defined in the spec.
func NewPatchSnapshotsSsIDReapParams() PatchSnapshotsSsIDReapParams {

	return PatchSnapshotsSsIDReapParams{}
}

// PatchSnapshotsSsIDReapParams contains all the bound params for the patch snapshots ss ID reap operation
// typically these are obtained from a http.Request
//
// swagger:parameters PatchSnapshotsSsIDReap
type PatchSnapshotsSsIDReapParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: body
	*/
	Cache bool
	/*
	  Required: true
	  In: path
	*/
	SsID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPatchSnapshotsSsIDReapParams() beforehand.
func (o *PatchSnapshotsSsIDReapParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body bool
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("cache", "body", "", err))
		} else {
			// no validation required on inline body
			o.Cache = body
		}
	}

	rSsID, rhkSsID, _ := route.Params.GetOK("ssId")
	if err := o.bindSsID(rSsID, rhkSsID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSsID binds and validates parameter SsID from path.
func (o *PatchSnapshotsSsIDReapParams) bindSsID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.SsID = raw

	return nil
}
