// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostVmmsHandlerFunc turns a function with the right signature into a post vmms handler
type PostVmmsHandlerFunc func(PostVmmsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostVmmsHandlerFunc) Handle(params PostVmmsParams) middleware.Responder {
	return fn(params)
}

// PostVmmsHandler interface for that can handle valid post vmms params
type PostVmmsHandler interface {
	Handle(PostVmmsParams) middleware.Responder
}

// NewPostVmms creates a new http.Handler for the post vmms operation
func NewPostVmms(ctx *middleware.Context, handler PostVmmsHandler) *PostVmms {
	return &PostVmms{Context: ctx, Handler: handler}
}

/*
	PostVmms swagger:route POST /vmms postVmms

Create a VMM in the pool
*/
type PostVmms struct {
	Context *middleware.Context
	Handler PostVmmsHandler
}

func (o *PostVmms) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostVmmsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostVmmsBadRequestBody post vmms bad request body
//
// swagger:model PostVmmsBadRequestBody
type PostVmmsBadRequestBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this post vmms bad request body
func (o *PostVmmsBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post vmms bad request body based on context it is used
func (o *PostVmmsBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostVmmsBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostVmmsBadRequestBody) UnmarshalBinary(b []byte) error {
	var res PostVmmsBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// PostVmmsBody post vmms body
//
// swagger:model PostVmmsBody
type PostVmmsBody struct {

	// enable reap
	EnableReap bool `json:"enableReap,omitempty"`

	// namespace
	Namespace string `json:"namespace,omitempty"`
}

// Validate validates this post vmms body
func (o *PostVmmsBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post vmms body based on context it is used
func (o *PostVmmsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostVmmsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostVmmsBody) UnmarshalBinary(b []byte) error {
	var res PostVmmsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
