// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostFunctionsHandlerFunc turns a function with the right signature into a post functions handler
type PostFunctionsHandlerFunc func(PostFunctionsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostFunctionsHandlerFunc) Handle(params PostFunctionsParams) middleware.Responder {
	return fn(params)
}

// PostFunctionsHandler interface for that can handle valid post functions params
type PostFunctionsHandler interface {
	Handle(PostFunctionsParams) middleware.Responder
}

// NewPostFunctions creates a new http.Handler for the post functions operation
func NewPostFunctions(ctx *middleware.Context, handler PostFunctionsHandler) *PostFunctions {
	return &PostFunctions{Context: ctx, Handler: handler}
}

/*
	PostFunctions swagger:route POST /functions postFunctions

Create a new function
*/
type PostFunctions struct {
	Context *middleware.Context
	Handler PostFunctionsHandler
}

func (o *PostFunctions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostFunctionsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostFunctionsBadRequestBody post functions bad request body
//
// swagger:model PostFunctionsBadRequestBody
type PostFunctionsBadRequestBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this post functions bad request body
func (o *PostFunctionsBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post functions bad request body based on context it is used
func (o *PostFunctionsBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostFunctionsBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostFunctionsBadRequestBody) UnmarshalBinary(b []byte) error {
	var res PostFunctionsBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
