// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PutSnapshotsHandlerFunc turns a function with the right signature into a put snapshots handler
type PutSnapshotsHandlerFunc func(PutSnapshotsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutSnapshotsHandlerFunc) Handle(params PutSnapshotsParams) middleware.Responder {
	return fn(params)
}

// PutSnapshotsHandler interface for that can handle valid put snapshots params
type PutSnapshotsHandler interface {
	Handle(PutSnapshotsParams) middleware.Responder
}

// NewPutSnapshots creates a new http.Handler for the put snapshots operation
func NewPutSnapshots(ctx *middleware.Context, handler PutSnapshotsHandler) *PutSnapshots {
	return &PutSnapshots{Context: ctx, Handler: handler}
}

/*
	PutSnapshots swagger:route PUT /snapshots putSnapshots

Put snapshot (copy)
*/
type PutSnapshots struct {
	Context *middleware.Context
	Handler PutSnapshotsHandler
}

func (o *PutSnapshots) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutSnapshotsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PutSnapshotsBadRequestBody put snapshots bad request body
//
// swagger:model PutSnapshotsBadRequestBody
type PutSnapshotsBadRequestBody struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this put snapshots bad request body
func (o *PutSnapshotsBadRequestBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this put snapshots bad request body based on context it is used
func (o *PutSnapshotsBadRequestBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PutSnapshotsBadRequestBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutSnapshotsBadRequestBody) UnmarshalBinary(b []byte) error {
	var res PutSnapshotsBadRequestBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
