// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewPutSnapshotsSsIDMincoreParams creates a new PutSnapshotsSsIDMincoreParams object
//
// There are no default values defined in the spec.
func NewPutSnapshotsSsIDMincoreParams() PutSnapshotsSsIDMincoreParams {

	return PutSnapshotsSsIDMincoreParams{}
}

// PutSnapshotsSsIDMincoreParams contains all the bound params for the put snapshots ss ID mincore operation
// typically these are obtained from a http.Request
//
// swagger:parameters PutSnapshotsSsIDMincore
type PutSnapshotsSsIDMincoreParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: query
	*/
	Source *string
	/*
	  Required: true
	  In: path
	*/
	SsID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPutSnapshotsSsIDMincoreParams() beforehand.
func (o *PutSnapshotsSsIDMincoreParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qSource, qhkSource, _ := qs.GetOK("source")
	if err := o.bindSource(qSource, qhkSource, route.Formats); err != nil {
		res = append(res, err)
	}

	rSsID, rhkSsID, _ := route.Params.GetOK("ssId")
	if err := o.bindSsID(rSsID, rhkSsID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSource binds and validates parameter Source from query.
func (o *PutSnapshotsSsIDMincoreParams) bindSource(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Source = &raw

	return nil
}

// bindSsID binds and validates parameter SsID from path.
func (o *PutSnapshotsSsIDMincoreParams) bindSsID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.SsID = raw

	return nil
}
