# coding: utf-8

"""
    faasnap

    FaaSnap API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Layer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'position': 'int',
        'from_diff': 'str'
    }

    attribute_map = {
        'position': 'position',
        'from_diff': 'fromDiff'
    }

    def __init__(self, position=None, from_diff=None, _configuration=None):  # noqa: E501
        """Layer - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._position = None
        self._from_diff = None
        self.discriminator = None

        if position is not None:
            self.position = position
        if from_diff is not None:
            self.from_diff = from_diff

    @property
    def position(self):
        """Gets the position of this Layer.  # noqa: E501


        :return: The position of this Layer.  # noqa: E501
        :rtype: int
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this Layer.


        :param position: The position of this Layer.  # noqa: E501
        :type: int
        """

        self._position = position

    @property
    def from_diff(self):
        """Gets the from_diff of this Layer.  # noqa: E501


        :return: The from_diff of this Layer.  # noqa: E501
        :rtype: str
        """
        return self._from_diff

    @from_diff.setter
    def from_diff(self, from_diff):
        """Sets the from_diff of this Layer.


        :param from_diff: The from_diff of this Layer.  # noqa: E501
        :type: str
        """

        self._from_diff = from_diff

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Layer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Layer):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Layer):
            return True

        return self.to_dict() != other.to_dict()
