# coding: utf-8

"""
    faasnap

    FaaSnap API  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.vm1 import VM1  # noqa: E501
from swagger_client.rest import ApiException


class TestVM1(unittest.TestCase):
    """VM1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVM1(self):
        """Test VM1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.vm1.VM1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
