// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Function function
//
// swagger:model Function
type Function struct {

	// func name
	// Required: true
	FuncName *string `json:"func_name"`

	// image
	Image string `json:"image,omitempty"`

	// kernel
	Kernel string `json:"kernel,omitempty"`

	// mem size
	MemSize int64 `json:"mem_size,omitempty"`

	// vcpu
	Vcpu int64 `json:"vcpu,omitempty"`
}

// Validate validates this function
func (m *Function) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFuncName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Function) validateFuncName(formats strfmt.Registry) error {

	if err := validate.Required("func_name", "body", m.FuncName); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this function based on context it is used
func (m *Function) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Function) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Function) UnmarshalBinary(b []byte) error {
	var res Function
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
