// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// VM VM
//
// swagger:model VM
type VM struct {

	// state
	State string `json:"state,omitempty"`

	// vm conf
	VMConf interface{} `json:"vmConf,omitempty"`

	// vm Id
	// Required: true
	VMID *string `json:"vmId"`

	// vm path
	VMPath string `json:"vmPath,omitempty"`
}

// Validate validates this VM
func (m *VM) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVMID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VM) validateVMID(formats strfmt.Registry) error {

	if err := validate.Required("vmId", "body", m.VMID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this VM based on context it is used
func (m *VM) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VM) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VM) UnmarshalBinary(b []byte) error {
	var res VM
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
